max_width = 100
hard_tabs = false
tab_spaces = 4
edition = "2021"
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
reorder_imports = true
fn_single_line = false
match_block_trailing_comma = true
trailing_comma = "Vertical"
normalize_comments = true
wrap_comments = true
