name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  format:
    name: Rustfmt Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - run: cargo fmt --all -- --check

  build-and-test:
    name: Build and Test
    needs: format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.90.0
          targets: wasm32-unknown-unknown
          components: clippy
      - run: cargo build --release --target wasm32-unknown-unknown
      - run: cargo test --locked
      - run: cargo clippy --lib --locked -- -D warnings
